Added put get

diff --git a/src/get b/src/get
--- a/src/get
+++ b/src/get
@@ -7,18 +7,25 @@ log_dir="$DIR/../env/logs/deploy"
 results_dir="$DIR/../env/results/$(date +%Y.%m.%d-%H:%M:%S)"
 ips_path="$DIR/../env/ips.txt"
 mkdir -p "$log_dir"
+mkdir -p "$results_dir"
 logs=''
 
+origin=$1
+default_target=$results_dir/$counter.$origin
+target=${2:-$default_target}
 
 while read IP; do
     log_path="$log_dir/$counter.log"
-    scp -o stricthostkeychecking=no \
-        -o BatchMode=yes \
-        -o EscapeChar=none \
-        -o ControlMaster=auto \
-        -o ControlPersist=yes \
-        -o ControlPath=~/.ssh/confine-%r-%h-%p \
-        root@[$IP]:$1 $results_dir/$counter.pcap &> "$log_path" &
+    {
+        echo "Going to copy root@[$IP]:$origin $target" >&2
+        scp -o stricthostkeychecking=no \
+            -o BatchMode=yes \
+            -o EscapeChar=none \
+            -o ControlMaster=auto \
+            -o ControlPersist=yes \
+            -o ControlPath=~/.ssh/confine-%r-%h-%p \
+            root@[$IP]:$origin $target && echo "Success on $IP" || echo "Failure on $IP" >&2
+    } &> "$log_path" &
     counter=$(($counter+1))
     logs="$logs $log_path"
 done < <(cat "$ips_path")
diff --git a/src/put b/src/put
--- a/src/put
+++ b/src/put
@@ -12,13 +12,16 @@ logs=''
 
 while read IP; do
     log_path="$log_dir/$counter.log"
-    scp -o stricthostkeychecking=no \
-        -o BatchMode=yes \
-        -o EscapeChar=none \
-        -o ControlMaster=auto \
-        -o ControlPersist=yes \
-        -o ControlPath=~/.ssh/confine-%r-%h-%p \
-        $1 root@[$IP]:${2} &> "$log_path" &
+    {
+        echo "Going to copy $1 to root@[$IP]:${2}" >&2
+        scp -o stricthostkeychecking=no \
+            -o BatchMode=yes \
+            -o EscapeChar=none \
+            -o ControlMaster=auto \
+            -o ControlPersist=yes \
+            -o ControlPath=~/.ssh/confine-%r-%h-%p \
+            $1 root@[$IP]:${2} && echo "Success on $IP" || echo "Failure on $IP" >&2
+    } &> "$log_path" &
     counter=$(($counter+1))
     logs="$logs $log_path"
 done < <(cat "$ips_path")
diff --git a/src/run b/src/run
--- a/src/run
+++ b/src/run
@@ -20,6 +20,7 @@ function run () {
             -p "$ORIGIN" root@[$IP]:/dev/shm/$TARGET
         CMD="/dev/shm/$TARGET"
     else
+        shift;
         CMD="$@"
     fi
     echo "Going to run [$IP] $CMD" >&2
@@ -29,8 +30,7 @@ function run () {
         -o ControlMaster=auto \
         -o ControlPersist=yes \
         -o ControlPath=~/.ssh/confine-%r-%h-%p \
-        root@$IP "$CMD"
-    echo "Clossing [$IP]" >&2
+        root@$IP "$CMD" && echo "Success on $IP" || echo "Failure on $IP" >&2
 }
 export -f run
 
